### ISSUE TITLE
저자 등록 방법

### ISSUE THREAD

**Issue by seopbo** [lassl/lassl.github.io#2]
이 글에서는 저자 정보를 등록하는 방법을 안내합니다.
저자 정보는 `_config.yml`에 기재해 두어야 합니다.
현재 저자 정보가 다음과 같다고 가정해 보겠습니다.

```
authors:
   boseop.kim:
    name: boseop.kim
    display_name:boseop.kim
    email: bsk0130@gmail.com
    web: https://velog.io/@aisolab
    facebook: https://www.facebook.com/boseob.kim.16
    description: "임베딩, 문장생성 등에 관심이 많습니다. GPT3 스케일의 거대 언어모델을 학습하고 있습니다. 딥러닝과 자연어 처리의 무궁무진한 가능성을 믿습니다."
```

여기에 저자 정보를 추가하려면 다음과 같이 추가로 입력합니다.

```
authors:
  boseop.kim:
    name: boseop.kim
    display_name: boseop.kim
    email: bsk0130@gmail.com
    web: https://velog.io/@aisolab
    facebook: https://www.facebook.com/boseob.kim.16
    description: "임베딩, 문장생성 등에 관심이 많습니다. GPT3 스케일의 거대 언어모델을 학습하고 있습니다. 딥러닝과 자연어 처리의 무궁무진한 가능성을 믿습니다."
  test:
    name: test
    display_name: test
    email: test@gmail.com
    web: test_url1
    facebook: test_url1
    description: "test"
```

이후 문서를 작성할 때 메타 정보 `author`에 위와 같이 등록한 저자 이름을 적으면 됩니다.
단 각 문서를 작성할 때 메타 정보에 입력하는 `author` 정보는 `_config.yml`에 반드시 사전 등록되어 있어야 합니다.
